// HISTORICAL V4 suite: password-auth journeys are retired. Use social-auth.cjs for the new entry flow.
const {chromium}=require('./tools/node_modules/playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');const crypto=require('node:crypto');const {execFileSync}=require('node:child_process');const Database=require('better-sqlite3');
const base='http://127.0.0.1:3000';
(async()=>{
 const password=crypto.randomBytes(18).toString('base64url');
 execFileSync('node',['scripts/create-admin.mjs'],{env:{...process.env,ADMIN_EMAIL:'qa-owner@example.invalid',ADMIN_PASSWORD:password}});
 const db=new Database('data/yemreact.sqlite');db.pragma('foreign_keys=ON');const beforeEvent=db.prepare('SELECT COALESCE(MAX(id),0) as n FROM events').get().n;
 const browser=await chromium.launch({args:['--no-sandbox','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],serviceWorkers:'block'});const page=await context.newPage();
 // Playwright APIRequest does not implement Chromium's secure-cookie localhost exception.
 const api=Object.fromEntries(['get','post','delete'].map(method=>[method,async(url,options={})=>context.request[method](url,{...options,headers:{...options.headers,Cookie:(await context.cookies()).map(c=>c.name+'='+c.value).join('; ')}})]));
 const result={checks:[],routes:[],errors:[],responsive:[]};const uploaded=[];
 page.on('pageerror',e=>result.errors.push(e.message));
 const go=async route=>{const r=await page.goto(base+route,{waitUntil:'networkidle'});await page.locator('h1:visible').first().waitFor();return r;};
 try{
 for(const route of ['/','/library','/saved','/about','/login','/admin','/offline',...Array.from({length:12},(_,i)=>'/r/YR-'+String(i+1).padStart(4,'0'))]){const r=await go(route);assert.equal(r.status(),200);result.routes.push({route,status:r.status()});}
 const nf=await page.goto(base+'/r/NOT-FOUND');assert.equal(nf.status(),404);result.missingStatus=nf.status();await page.getByRole('heading',{name:'عاد وين راحت؟'}).waitFor();result.checks.push('19 page routes + missing-content fallback');
 await go('/');await page.getByRole('button',{name:'تخصيص المظهر'}).click();await page.getByRole('button',{name:'ليلي',exact:true}).click();await page.getByRole('button',{name:'إغلاق',exact:true}).click();await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({path:'verification/v4/home-dark.png'});
 await page.getByRole('button',{name:'تخصيص المظهر'}).click();await page.getByRole('button',{name:'نهاري',exact:true}).click();await page.getByRole('button',{name:'أخضر',exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--accent')),'#367567');await page.getByRole('button',{name:'كهرماني',exact:true}).click();await page.getByRole('button',{name:'إغلاق',exact:true}).click();result.checks.push('Theme persistence and accent customization');
 await page.getByLabel('ابحث عن موقف',{exact:true}).fill('خبر صادم');await page.getByRole('button',{name:'ابحث في المكتبة'}).click();await page.waitForURL('**/library?q=*');assert.equal(await page.locator('.reaction-card').count(),1);
 await go('/library');assert.equal(await page.locator('.category-tabs').count(),0);assert.equal(await page.locator('.reaction-card').count(),8);await page.getByRole('button',{name:'أظهر المزيد'}).click();assert.equal(await page.locator('.reaction-card').count(),12);
 await page.getByLabel('أقصى مدة').selectOption('3');assert.equal(await page.locator('.reaction-card').count(),7);await go('/library?cat=reject');await page.getByLabel('أقصى مدة').selectOption('3');assert.equal(await page.locator('.reaction-card').count(),0);await page.getByRole('button',{name:'مسح الفلاتر'}).click();await page.waitForURL('**/library');result.checks.push('Live Arabic search, category + duration filters, sorting controls and load more');
 await go('/library?q='+encodeURIComponent('يا ساتر'));await page.getByRole('button',{name:'حفظ يا ساتر!',exact:true}).click();await go('/saved');assert.equal(await page.locator('.reaction-card').count(),1);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('.reaction-card').count(),1);result.checks.push('Guest bookmarks survive navigation and reload');
 await page.locator('.card-preview').filter({hasText:'يا ساتر!'}).click();await page.locator('dialog[open] video').evaluate(v=>v.play());await page.waitForTimeout(600);assert.ok(await page.locator('dialog[open] video').evaluate(v=>v.currentTime>0));
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'خذها',exact:true}).click();const download=await downloadPromise;await download.saveAs('.cache/qa-download.mp4');assert.ok(fs.statSync('.cache/qa-download.mp4').size>1000);
 await page.getByRole('button',{name:'شارك',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/\/r\/YR-0001$/);
 await page.getByRole('button',{name:'الرياكشن التالي',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);result.checks.push('Native-dialog preview, working video playback, MP4 download, share/copy and keyboard Escape');
 let response=await api.get(base+'/api/admin');assert.equal(response.status(),401);response=await api.post(base+'/api/reactions',{headers:{Origin:base},data:{}});assert.equal(response.status(),401);response=await api.post(base+'/api/auth',{headers:{Origin:'https://untrusted.example'},data:{}});assert.equal(response.status(),403);result.checks.push('Anonymous admin denial and cross-origin mutation denial');
 await go('/login');await page.getByRole('button',{name:'حساب جديد',exact:true}).click();await page.getByLabel('اسمك',{exact:true}).fill('عضو الاختبار');await page.getByLabel('البريد الإلكتروني',{exact:true}).fill('qa-member@example.invalid');await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'إنشاء الحساب',exact:true}).click();await page.waitForURL('**/saved');
 response=await api.get(base+'/api/admin');assert.equal(response.status(),403);response=await api.post(base+'/api/reactions',{headers:{Origin:base},data:{}});assert.equal(response.status(),403);
 await go('/library?q='+encodeURIComponent('يا ساتر'));await page.getByRole('button',{name:'حفظ يا ساتر!',exact:true}).click();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'إزالة يا ساتر! من المحفوظات'}).waitFor();const remote=await (await api.get(base+'/api/saved')).json();assert.ok(remote.saved.includes('YR-0001'));result.checks.push('Real signup, scrypt-backed login session, member authorization denial and server bookmarks');
 await api.delete(base+'/api/auth',{headers:{Origin:base}});
 const login=await api.post(base+'/api/auth',{headers:{Origin:base},data:{mode:'login',email:'qa-owner@example.invalid',password}});assert.equal(login.status(),200);
 await go('/admin');await page.getByRole('button',{name:'رياكشن جديد',exact:true}).waitFor();await page.screenshot({path:'verification/v4/admin-owner.png',fullPage:true});
 await page.getByRole('button',{name:'رياكشن جديد',exact:true}).click();await page.getByLabel('الاقتباس',{exact:true}).fill('QA قصاصة اختبار');await page.getByLabel('متى نستخدمه؟',{exact:true}).fill('هذا موقف اختبار آلي، سيحذف بعد الفحص');await page.getByLabel('كلمات البحث',{exact:false}).fill('اختبار، فحص');await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'اختيار النموذج 2'}).click();await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'نشر القصاصة',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'الرياكشنات',exact:true}).click();await page.getByRole('button',{name:'تعديل QA قصاصة اختبار',exact:true}).click();await page.getByLabel('الاقتباس',{exact:true}).fill('QA قصاصة معدّلة');await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'نشر القصاصة',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'حذف QA قصاصة معدّلة',exact:true}).click();await page.getByRole('button',{name:'نعم، احذفها'}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'حذف QA قصاصة معدّلة'}).count(),0);result.checks.push('Owner creates, edits and deletes via validated three-step editor');
 const upload=await api.post(base+'/api/upload',{headers:{Origin:base},multipart:{file:{name:'qa.mp4',mimeType:'video/mp4',buffer:fs.readFileSync('public/media/demo-1.mp4')}}});assert.equal(upload.status(),200);const media=(await upload.json()).url;uploaded.push(media.split('/').pop());
 const range=await api.get(base+media,{headers:{Range:'bytes=0-31'}});assert.equal(range.status(),206);assert.equal((await range.body()).length,32);
 const invalidUpload=await api.post(base+'/api/upload',{headers:{Origin:base},multipart:{file:{name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg><script>alert(1)</script></svg>')}}});assert.equal(invalidUpload.status(),400);result.checks.push('Authenticated media upload, signature rejection and video Range seeking');
 await page.getByRole('button',{name:'المستخدمون',exact:true}).click();await page.getByText('qa-member@example.invalid',{exact:true}).waitFor();await page.getByRole('button',{name:'سجل العمليات',exact:true}).click();await page.getByText('آخر 40 عملية إدارية',{exact:true}).waitFor();result.checks.push('Owner-only users list and audit log');
 await api.delete(base+'/api/auth',{headers:{Origin:base}});
 for(const width of [320,375,768,1024,1440,1920,3840]){await page.setViewportSize({width,height:900});for(const route of ['/','/library','/r/YR-0001','/about','/saved','/login','/admin']){await go(route);const dims=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));result.responsive.push({route,width,...dims});assert.ok(dims.document<=width+1,`Overflow ${route} at ${width}: ${dims.document}`);if(width===320&&route==='/')await page.screenshot({path:'verification/v4/home-320.png',fullPage:true});}}
 await page.setViewportSize({width:1440,height:1000});await go('/');await page.screenshot({path:'verification/v4/home-desktop.png',fullPage:true});await page.screenshot({path:'verification/v4/home-hero.png'});await go('/library');await page.screenshot({path:'verification/v4/library.png',fullPage:true});await go('/r/YR-0001');await page.screenshot({path:'verification/v4/detail.png',fullPage:true});result.completed=true;
 }catch(e){result.failure=e.stack;process.exitCode=1;console.error(e);}
 finally{fs.writeFileSync('verification/v4/flows.json',JSON.stringify(result,null,2));await browser.close();db.prepare("DELETE FROM reactions WHERE json_extract(data,'$.caption') LIKE 'QA %'").run();db.prepare("DELETE FROM audit WHERE user_id IN (SELECT id FROM users WHERE email LIKE 'qa-%@example.invalid')").run();db.prepare("DELETE FROM users WHERE email LIKE 'qa-%@example.invalid'").run();db.prepare('DELETE FROM events WHERE id>?').run(beforeEvent);for(const file of uploaded){try{fs.unlinkSync('data/uploads/'+file);}catch{}}db.close();}
 console.log(JSON.stringify(result,null,2));
})();
